### ISSUE TITLE
Introduce The Library

### ISSUE THREAD

**Issue by caiyunfeide** [Dronecode/DronecodeSDK-Swift#101]
I want to introduce the library into the existing OC project, may I ask what method is needed? The Carthage import library used in the demo often times out of time. Can we download the library separately and introduce it into the demo?

**Comment by caiyunfeide** [comment]
I want to introduce this library into the existing OC project, which USES CocoaPods instead of Carthage

**Comment by caiyunfeide** [comment]
It Mean The Project Use Objective-C

**Comment by caiyunfeide** [comment]
I may trouble you again if I have any problems in the future. Thank you for your advice

**Comment by JonasVautherin** [comment]
No worries! Good luck!
