### ISSUE TITLE
Cannot connect to jMavSim running inside the LAN from iPhone, but QGC can.

### ISSUE THREAD

**Issue by SandW** [Dronecode/DronecodeSDK-Swift#103]
Beforehand, in iPhone emulator, the swift demo app can connect to the drone simulated in local jMavSim. 

Now, the problem is:
1. jMavSim started and set to broadcast MAVLINK to ports 14550 and 14540 in PC1.
2. QGC can connect to the drone in the jMavSim from PC2 in the same LAN.
3. The swift demo app running on real iPhone in Macbook(**the 3rd computer**) **cannot** connect to jMavSim running on PC1.

Best and Thanks!

**Comment by julianoes** [comment]
1. Have you checked that your LAN and Wifi network are bridged?
You can check this by connecting using QGC on a computer in the Wifi.

2. What's the output in the command line when you start the iOS app?

If you're in China, and you see `no route to host`, it could be that your iPhone is not allowing the network connection and you need something like this:
https://github.com/YUNEEC/Yuneec-SDK-iOS/blob/0112e753abfd3dcb539d083e160c4c73ee494668/Yuneec_SDK_iOS/YNCSDKConnection.mm#L134-L153

And you could probably also check if you have connection, e.g. like this:
https://stackoverflow.com/questions/1083701/how-to-check-for-an-active-internet-connection-on-ios-or-macos

**Comment by caiyunfeide** [comment]
In my code I can connect to 'http://www.google.com' ,but can't connect to 'https://192.168.42.1/' , Now I can't connect the iphone  the jmavsim. What should I do

**Comment by caiyunfeide** [comment]
When I connect to 'https://192.168.42.1/' , Remind me ' Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." '

**Comment by JonasVautherin** [comment]
@caiyunfeide: Is it related to @SandW question above? It is not the same username, I am confused :confused:

**Comment by caiyunfeide** [comment]
We work in a team sorry.

**Comment by JonasVautherin** [comment]
Right. So you haven't answered most of our questions, please have a look again and answer them.

If I had to guess, I would say that it looks like your iPhone is connected to the Internet, but that it is not on the same network as the computer running jmavsim (192.168.42.1). Did it ever work? @SandW question above sounds like at some point, your setup was working.

**Comment by SandW** [comment]
> So you're saying that it was working before, aren't you? What did you change in the setup?

It has not worked till now.

> Did 14540 ever work, or were you always using 14550?

Both ports are not work.

> And how do you set jMavSim to broadcast on 14550 and 14540?

I set jMavSim to broadcast in the PX4 parameters from QGC in PC2. 

> 1. Have you checked that your LAN and Wifi network are bridged?
>    You can check this by connecting using QGC on a computer in the Wifi.

What I meant for LAN = Wifi. I can connect QGC with jMavSim in the Wifi as I described in the first post.

**Comment by julianoes** [comment]
Ok, can you paste the printf/debug output in XCode?

**Comment by caiyunfeide** [comment]
**PC1: Linux,Ubuntu16.04,jMavSim broadcasting Mavlink on ports 14550 and 14540. IP address is 192.168.50.44.**

Macbook: Xcode, iPhone Simulator,jMavSim broadcasting Mavlink on ports 14550 and 14540. IP address is 192.168.50.238.

Real iPhone.

—————————————

- Successful connection:

Settings in DronecodeSDK-Swift: ipString = ”localhost" , portNumber = 50051.
Xcode command line output using iPhone Simulator on Macbook :

> 2019-01-08 14:04:02.120530+0800 DronecodeSDKSwiftDemo[66221:1015312] creating player instance using shared library
> Running backend in background (MAVLink port: 14540)
> [02:04:02|Info ] DronecodeSDK version: 0.7.3 (dronecode_sdk_impl.cpp:24)
> [02:04:02|Warn ] No system found. (dronecode_sdk_impl.cpp:222)
> [02:04:02|Debug] New: System ID: 0 Comp ID: 0 (dronecode_sdk_impl.cpp:285)
> [02:04:03|Info ] Server set to listen on 0.0.0.0:50051 (grpc_server.cpp:39)
> [02:04:03|Info ] Server started (grpc_server.cpp:23)
> [02:04:03|Info ] Waiting to discover system... (connection_initiator.h:57)
> [02:04:03|Info ] New device on: 127.0.0.1:14580 (udp_connection.cpp:200)
> [02:04:03|Debug] Component Autopilot (1) added. (system_impl.cpp:372)
> [02:04:03|Debug] Discovered 1 component(s) (UUID: 5283920058631409231) (system_impl.cpp:512)
> [02:04:03|Info ] System discovered [UUID: 5283920058631409231] (connection_initiator.h:61)
> Drone Connected with UUID : 5283920058631409231
> [02:04:03|Debug] MAVLink: info: data link #0 lost (system_impl.cpp:283)
> [02:04:03|Debug] MAVLink: info: data link #0 regained (system_impl.cpp:283)

—————————————

- Failed connnection:

1. jMavSim was running on Macbook. The ipString is set to 192.168.50.*(except for localhost) and port is set to 14550 in the DronecodeSDK-Swift App running in the simulator. The drone status cannot be obtained after connection. Please see the screenshot below.

![pasted graphic](https://user-images.githubusercontent.com/15375324/50815168-237d2f80-1357-11e9-9f66-ef1b3f48afcc.png)




Xcode command line output using iPhone Simulator on Macbook :

> 2019-01-08 14:52:36.088880+0800 DronecodeSDKSwiftDemo[55181:1200041] creating player instance using shared library
> Running backend in background (MAVLink port: 14540)
> [02:52:36|Info ] DronecodeSDK version: 0.7.3 (dronecode_sdk_impl.cpp:24)
> [02:52:36|Warn ] No system found. (dronecode_sdk_impl.cpp:222)
> [02:52:36|Debug] New: System ID: 0 Comp ID: 0 (dronecode_sdk_impl.cpp:285)
> [02:52:36|Info ] Server set to listen on 0.0.0.0:50051 (grpc_server.cpp:39)
> [02:52:36|Info ] Server started (grpc_server.cpp:23)
> [02:52:36|Info ] Waiting to discover system... (connection_initiator.h:57)
> [02:52:36|Info ] New device on: 127.0.0.1:14580 (udp_connection.cpp:200)
> [02:52:36|Debug] Component Autopilot (1) added. (system_impl.cpp:372)
> [02:52:36|Debug] Discovered 1 component(s) (UUID: 5283920058631409231) (system_impl.cpp:512)
> [02:52:36|Info ] System discovered [UUID: 5283920058631409231] (connection_initiator.h:61)
> Drone Connected with UUID : 5283920058631409231
> [02:52:37|Debug] MAVLink: info: data link #1 lost (system_impl.cpp:283)
> [02:52:37|Debug] MAVLink: info: data link #1 regained (system_impl.cpp:283)




2. jMavSim was running on PC1(Linux Ubuntu 16.04) or on Macbook. The ipString is set to 192.168.50.44/192.168.50.238 and port is set to 14550 in the DronecodeSDK-Swift App running in the simulator or in a real iPhone. The outputs from 2 different methods are the same as follows.

A real iPhone is working in debugging mode. Xcode command line output on Macbook :

> 2019-01-08 14:47:45.292938+0800 DronecodeSDKSwiftDemo[3825:1380363] [DYMTLInitPlatform] platform initialization successful
> 2019-01-08 14:47:45.533931+0800 DronecodeSDKSwiftDemo[3825:1380315] creating player instance using shared library
> Running backend in background (MAVLink port: 14540)
> [02:47:45|Info ] DronecodeSDK version: 0.7.3 (dronecode_sdk_impl.cpp:24)
> [02:47:45|Warn ] No system found. (dronecode_sdk_impl.cpp:222)
> [02:47:45|Debug] New: System ID: 0 Comp ID: 0 (dronecode_sdk_impl.cpp:285)
> [02:47:45|Info ] Server set to listen on 0.0.0.0:50051 (grpc_server.cpp:39)
> [02:47:45|Info ] Server started (grpc_server.cpp:23)
> [02:47:45|Info ] Waiting to discover system... (connection_initiator.h:57)
> [02:47:46|Error] No known remotes (udp_connection.cpp:130)
> [02:47:46|Error] send fail (dronecode_sdk_impl.cpp:90)

 Xcode command line output using iPhone Simulator on Macbook :

> 2019-01-08 14:13:16.757712+0800 DronecodeSDKSwiftDemo[83213:1053962] creating player instance using shared library
> Running backend in background (MAVLink port: 14540)
> [02:13:16|Info ] DronecodeSDK version: 0.7.3 (dronecode_sdk_impl.cpp:24)
> [02:13:16|Warn ] No system found. (dronecode_sdk_impl.cpp:222)
> [02:13:16|Debug] New: System ID: 0 Comp ID: 0 (dronecode_sdk_impl.cpp:285)
> [02:13:16|Info ] Server set to listen on 0.0.0.0:50051 (grpc_server.cpp:39)
> [02:13:16|Info ] Server started (grpc_server.cpp:23)
> [02:13:16|Info ] Waiting to discover system... (connection_initiator.h:57)
> [02:13:17|Error] No known remotes (udp_connection.cpp:130)
> [02:13:17|Error] send fail (dronecode_sdk_impl.cpp:90)

**Comment by julianoes** [comment]
Ok, so I think there is some confusion about the different pieces having to connect.

So the Swift "frontend" should always connect to the "backend" on localhost:50051. I don't think there is a need to change that (unless you completely want to change the architecture of the deployment so that the backend runs on a computer and only the frontend on the phone).

Then, you need to make sure that the drone connects to the backend on the phone, and there are two ways for that. Either you set the param `MAV_BROADCAST` to `1`  which means that the MAVLink instances on 14540 and 14550 automatically try to broadcast the heartbeats until a ground station or the SDK picks them up.
Or alternatively, you can specify the IP of where the MAVLink traffic should go (e.g. the phone) using `-t 192.168.50.xxx` in the `mavlink start` command here:
https://github.com/PX4/Firmware/blob/541b9626543fa95384bbd6edecf4080c004ff42e/ROMFS/px4fmu_common/init.d-posix/rcS#L228
and here:
https://github.com/PX4/Firmware/blob/541b9626543fa95384bbd6edecf4080c004ff42e/ROMFS/px4fmu_common/init.d-posix/rcS#L240

**Comment by SandW** [comment]
> Ok, so I think there is some confusion about the different pieces having to connect.
> 
Yes, we thought that the 50051 is the local SITL port.  Thanks!

> So the Swift "frontend" should always connect to the "backend" on localhost:50051. I don't think there is a need to change that (unless you completely want to change the architecture of the deployment so that the backend runs on a computer and only the frontend on the phone).
> 

As you mentioned above, we do not need to change 50051 anymore. OK.

> Then, you need to make sure that the drone connects to the backend on the phone, and there are two ways for that. Either you set the param `MAV_BROADCAST` to `1` which means that the MAVLink instances on 14540 and 14550 automatically try to broadcast the heartbeats until a ground station or the SDK picks them up.

The SDK does not pick up anything from MAVLink. That is the key point of this issue. The apps running the SDK sample in iPhone does not pick anything up, even the parameters had changed and QGC can connect to the SITL.

> Or alternatively, you can specify the IP of where the MAVLink traffic should go (e.g. the phone) using `-t 192.168.50.xxx` in the `mavlink start` command here:
> https://github.com/PX4/Firmware/blob/541b9626543fa95384bbd6edecf4080c004ff42e/ROMFS/px4fmu_common/init.d-posix/rcS#L228
> and here:
> https://github.com/PX4/Firmware/blob/541b9626543fa95384bbd6edecf4080c004ff42e/ROMFS/px4fmu_common/init.d-posix/rcS#L240

We have not tested this method yet. We would like to use the SITL connection since it is really comfortable for development.

**Comment by SandW** [comment]
> Note that you can also use the [mavlink router](https://github.com/intel/mavlink-router) instead of manually editing the rcS file.

Have you tested the real iPhone sample of dronecodesdk_swift without using mavlink router? Can you share your apps with us?

**Comment by JonasVautherin** [comment]
> Have you tested the real iPhone sample of dronecodesdk_swift without using mavlink router? Can you share your apps with us?

The SDK is expecting to receive MAVLink messages from the autopilot. By enabling the mavlink broadcast, depending on the network topology, the SDK will receive them. But on some networks, that won't work. And it is just a limitation of broadcasting over the network, and it has nothing to do with the SDK.

If the MAVLink broadcast doesn't work, you can tell SITL to send the messages directly to your iPhone, either by setting `-t` in the `rcS` file of SITL (just edit the file, and build SITL again), or by using mavlink router.

I personally use both: sometimes the mavlink router, sometimes the `-t` argument (for instance in my [gazebo-headless docker image](https://github.com/JonasVautherin/px4-gazebo-headless)).

**Comment by roseyangyu** [comment]
> https://github.com/PX4/Firmware/blob/541b9626543fa95384bbd6edecf4080c004ff42e/ROMFS/px4fmu_common/init.d-posix/rcS#L228
> and here:
> https://github.com/PX4/Firmware/blob/541b9626543fa95384bbd6edecf4080c004ff42e/ROMFS/px4fmu_common/init.d-posix/rcS#L240

I have used v1.8.0.I can't find this file.I must change my version to v1.9.0? @julianoes

**Comment by SandW** [comment]
We have solved the issue. The solution is:
```
mavlink stop-all
mavlink start -o15450 -t {LAN IP} -r 4000000
```
Thank you  @JonasVautherin @julianoes  very much!

**Comment by JonasVautherin** [comment]
> I have used v1.8.0.

Oh that's a good point. In v1.8.0, it is in `posix-configs/SITL/init/ekf2/iris`. So you could go add `-t {LAN IP}` there, too.

Glad to see that you found a way!
