### ISSUE TITLE
Add method for cancelling mission upload/download process

### ISSUE THREAD

**Issue by byuarus** [Dronecode/DronecodeSDK-Swift#106]
For big missions, mission upload/download process could take a significant time. We need to have an option to cancel a mission upload and start uploading another mission. If we try to upload/download while upload/download is in progress, the request will fail.

**Comment by julianoes** [comment]
Done in C++: https://github.com/Dronecode/DronecodeSDK/pull/626

**Comment by JonasVautherin** [comment]
Done in `0.4.1`.
