### ISSUE TITLE
Error building SDK from Carthage

### ISSUE THREAD

**Issue by douglaswsilva** [Dronecode/DronecodeSDK-Swift#120]
Keep get this error when trying to run `carthage bootstrap --platform ios`:

```
3DR-000328:Downloads douglas$ cd /Users/douglas/Downloads/DronecodeSDK-Swift-master\ 2 
3DR-000328:DronecodeSDK-Swift-master 2 douglas$ carthage bootstrap --platform ios
*** Checking out grpc-swift at "0.8.1"
*** Checking out RxSwift at "4.5.0"
*** Downloading binary-only framework backend at "https://s3.eu-central-1.amazonaws.com/dronecode-sdk/backend.json"
*** xcodebuild output can be found in /var/folders/2d/t05mnyvs1ll3z81lgn1xlqgw0000gp/T/carthage-xcodebuild.nGAape.log
*** Downloading RxSwift.framework binary at "[4,5]"
***  Skipped installing RxSwift.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)."

    Falling back to building from the source
*** Building scheme "SwiftGRPC-Package" in SwiftGRPC-Carthage.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/douglas/Downloads/DronecodeSDK-Swift-master\ 2/Carthage/Checkouts/grpc-swift/SwiftGRPC-Carthage.xcodeproj -scheme SwiftGRPC-Package -configuration Release -derivedDataPath /Users/douglas/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/grpc-swift/0.8.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/2d/t05mnyvs1ll3z81lgn1xlqgw0000gp/T/grpc-swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/douglas/Downloads/DronecodeSDK-Swift-master 2/Carthage/Checkouts/grpc-swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/2d/t05mnyvs1ll3z81lgn1xlqgw0000gp/T/carthage-xcodebuild.nGAape.log
3DR-000328:DronecodeSDK-Swift-master 2 douglas$ 
```

NOTE: We're using XCode 10.1

**Comment by douglaswsilva** [comment]
[douglog.log](https://github.com/Dronecode/DronecodeSDK-Swift/files/3149893/douglog.log)

**Comment by JonasVautherin** [comment]
Seems like they released [gRPC-Swift 0.9.0](https://github.com/grpc/grpc-swift/releases/tag/0.9.0) with "fixes for Swift 5".

@douglaswsilva: would you mind [trying gRPC-Swift 0.9.0](https://github.com/Dronecode/DronecodeSDK-Swift/blob/master/Cartfile#L1)? Should be a matter of editing the SDK Cartfile and running Carthage again.

**Comment by byuarus** [comment]
@JonasVautherin I've just checked and I see that [gRPC-Swift 0.9.0](https://github.com/grpc/grpc-swift/releases/tag/0.9.0) doesn't work with the XCode 10.1 (Swift 4.2) but [the latest commit in master](https://github.com/grpc/grpc-swift/commit/67a5352f179751f6aef4e709c030308722f97073) works.

**Comment by JonasVautherin** [comment]
Oh, good find!

Just to recap then: it broke, but...
* We haven't changed the release of gRPC-Swift that we use
* We are still building with Swift 4.2

What could have changed that would break the build? Could it be a change in RxSwift? Like instead of `~> 4.0` should we fix it to some version?

**Comment by byuarus** [comment]
Hi @JonasVautherin, 
- I think that the Carthage was broken for a while when you have changed the version of gRPC-Swift that you use. I think it was the only issue for the Carthage builds. Please check my PR #122  that should fix Carthage support for the SDK. 
- Yes, we're still using XCode 10.1 and Swift 4.2. We can't migrate our code to Swift 5 and XCode 10.2 yet as some of our 3rd party libraries haven't done the migration.
