### ISSUE TITLE
Implement frontend mission

### ISSUE THREAD

**Issue by julianoes** [Dronecode/DronecodeSDK-Swift#4]
- [x] UploadMission
- [x] DownloadMission
- [x] StartMission
- [x] PauseMission
- [x] SetCurrentMissionItemIndex
- [x] GetCurrentMissionItemIndex
- [x] GetMissionCount
- [x] IsMissionFinished
- [x] SubscribeMissionProgress

**Comment by JonasVautherin** [comment]
That's resolved.
