### ISSUE TITLE
Implement frontend for camera

### ISSUE THREAD

**Issue by julianoes** [Dronecode/DronecodeSDK-Swift#5]
- [x] TakePhoto
- [x] StartPhotoInterval
- [x] StopPhotoInterval
- [x] StartVideo
- [x] StopVideo
- [x] StartVideoStreaming
- [x] StopVideoStreaming
- [x] SetMode
- [x] SubscribeMode
- [x] SetVideoStreamSettings
- [x] SubscribeVideoStreamInfo
- [x] SubscribeCaptureInfo
- [x] SubscribeCameraStatus
- [x] SubscribeCurrentSettings
- [x] SubscribePossibleSettings
- [x] SetSetting

**Comment by JonasVautherin** [comment]
Resolved.
