### ISSUE TITLE
Add camera features to Sample app

### ISSUE THREAD

**Issue by JonasVautherin** [Dronecode/DronecodeSDK-Swift#60]
Not all the features are implemented yet, but many of them are (like `takePhoto`, etc), as detailed in #5.

Would be nice to add them/some of them in the app already.

**Comment by JonasVautherin** [comment]
@ayameMBS Do you think you could have a look at this? So that the sample app would already have the structure to add the other features when they get implemented :-).

**Comment by Sushma7785** [comment]
@JonasVautherin I can start working on this if that is okay.

**Comment by JonasVautherin** [comment]
Thanks Sushma. Let's wait from a confirmation from @ayameMBS, maybe she already started that locally.

**Comment by ayameMBS** [comment]
Sorry for the late reply. No, I haven't start yet that implementation. So @Sushma7785  you can do it.

**Comment by JonasVautherin** [comment]
Not part of this repo anymore.
